# Keys
KL1 = []
KL2 = []
KO1 = [] 
KO2 = [] 
KO3 = []
KI1 = [] 
KI2 = []
KI3 = []

# Watch variables
WATCH_EXEC_STATUS = False
WATCH_READ_TIME = 0
WATCH_WRITE_TIME = 0
WATCH_BLOC_KASUMI = 0
WATCH_GLOBAL_KASUMI = 0
WATCH_CIPHER_TYPE = "ECB"
WATCH_BLOC_CIPHER = 0
WATCH_GLOBAL_CIPHER = 0
WATCH_PERCENTAGE = 0.001
WATCH_GLOBAL_TIME = 0
